---
- name: Create Resource List
  hosts: localhost
  gather_facts: false
  roles:
    - role: create_update_resource_list
  tags:
    - create_update_resource_list

- name: Update Resources
  hosts: localhost
  gather_facts: false
  roles:
    - role: update_resources
  tags:
    - update_resources
